language: ruby
rvm:
- 2.2

cache:
- directories:
  - .asset-cache
  - bower_components
  - vendor

before_install:
- nvm install 4
- npm install -g bower
- bower install
- if [[ $(git show --name-only) == *_assets/less* ]]; then rm -rf .asset-cache/sprockets; fi

script:
- set -e
- bundle exec jekyll build --verbose --trace
- set +e
- #bundle exec htmlproofer ./_site --allow-hash-href --check-html --http-status-ignore 0
- cd _site
- touch .nojekyll
- git init
- git config user.name "Travis-CI"
- git config user.email "travis@abemedia.co.uk"
- git add .
- git commit -m "Deployed to Github Pages"
- git push -f -u "https://${GH_TOKEN}@github.com/abemedia/geolocate-demo" HEAD:gh-pages > /dev/null 2>&1

git:
  depth: 10

notifications:
  email: false

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
